export const ENUM_MENU = {
  ERP_GESTAO: "ERP_GESTAO",
  ERP_GESTAO_EMPRESA: "ERP_GESTAO_EMPRESA",
  ERP_GESTAO_EMPRESA_MATRIZ: "ERP_GESTAO_EMPRESA_MATRIZ",
  ERP_GESTAO_EMPRESA_MATRIZ_EDIT: "ERP_GESTAO_EMPRESA_MATRIZ_EDIT",
  ERP_GESTAO_EMPRESA_AREAS: "ERP_GESTAO_EMPRESA_AREAS",
  ERP_GESTAO_EMPRESA_AREAS_ADD: "ERP_GESTAO_EMPRESA_AREAS_ADD",
  ERP_GESTAO_EMPRESA_AREAS_EDIT: "ERP_GESTAO_EMPRESA_AREAS_EDIT",
  ERP_GESTAO_EMPRESA_AREAS_DELETE: "ERP_GESTAO_EMPRESA_AREAS_DELETE",
  ERP_GESTAO_EMPRESA_STATUS: "ERP_GESTAO_EMPRESA_STATUS",
  ERP_GESTAO_EMPRESA_STATUS_ADD: "ERP_GESTAO_EMPRESA_STATUS_ADD",
  ERP_GESTAO_EMPRESA_STATUS_EDIT: "ERP_GESTAO_EMPRESA_STATUS_EDIT",
  ERP_GESTAO_EMPRESA_STATUS_DELETE: "ERP_GESTAO_EMPRESA_STATUS_DELETE",
  ERP_GESTAO_RH: "ERP_GESTAO_RH",
  ERP_GESTAO_RH_COLABORADORES: "ERP_GESTAO_RH_COLABORADORES",
  ERP_GESTAO_RH_COLABORADORES_ADD: "ERP_GESTAO_RH_COLABORADORES_ADD",
  ERP_GESTAO_RH_COLABORADORES_EDIT: "ERP_GESTAO_RH_COLABORADORES_EDIT",
  ERP_GESTAO_RH_COLABORADORES_DELETE: "ERP_GESTAO_RH_COLABORADORES_DELETE",
  ERP_GESTAO_RH_PERFIL: "ERP_GESTAO_RH_PERFIL",
  ERP_GESTAO_RH_PERFIL_ADD: "ERP_GESTAO_RH_PERFIL_ADD",
  ERP_GESTAO_RH_PERFIL_EDIT: "ERP_GESTAO_RH_PERFIL_EDIT",
  ERP_GESTAO_RH_PERFIL_DELETE: "ERP_GESTAO_RH_PERFIL_DELETE",
  ERP_GESTAO_PRODUTO: "ERP_GESTAO_PRODUTO",
  ERP_GESTAO_PRODUTO_EQUIPAMENTOS: "ERP_GESTAO_PRODUTO_EQUIPAMENTOS",
  ERP_GESTAO_PRODUTO_EQUIPAMENTOS_ADD: "ERP_GESTAO_PRODUTO_EQUIPAMENTOS_ADD",
  ERP_GESTAO_PRODUTO_EQUIPAMENTOS_EDIT: "ERP_GESTAO_PRODUTO_EQUIPAMENTOS_EDIT",
  ERP_GESTAO_PRODUTO_EQUIPAMENTOS_DELETE:
    "ERP_GESTAO_PRODUTO_EQUIPAMENTOS_DELETE",
  ERP_GESTAO_PRODUTO_TIPOS_EQUIPAMENTOS:
    "ERP_GESTAO_PRODUTO_TIPOS_EQUIPAMENTOS",
  ERP_GESTAO_PRODUTO_TIPOS_EQUIPAMENTOS_ADD:
    "ERP_GESTAO_PRODUTO_TIPOS_EQUIPAMENTOS_ADD",
  ERP_GESTAO_PRODUTO_TIPOS_EQUIPAMENTOS_EDIT:
    "ERP_GESTAO_PRODUTO_TIPOS_EQUIPAMENTOS_EDIT",
  ERP_GESTAO_PRODUTO_TIPOS_EQUIPAMENTOS_DELETE:
    "ERP_GESTAO_PRODUTO_TIPOS_EQUIPAMENTOS_DELETE",
  ERP_GESTAO_CLIENTES: "ERP_GESTAO_CLIENTES",
  ERP_GESTAO_CLIENTES_CADASTRADOS: "ERP_GESTAO_CLIENTES_CADASTRADOS",
  ERP_GESTAO_CLIENTES_CADASTRADOS_ADD: "ERP_GESTAO_CLIENTES_CADASTRADOS_ADD",
  ERP_GESTAO_CLIENTES_CADASTRADOS_EDIT: "ERP_GESTAO_CLIENTES_CADASTRADOS_EDIT",
  ERP_GESTAO_CLIENTES_CADASTRADOS_DELETE:
    "ERP_GESTAO_CLIENTES_CADASTRADOS_DELETE",
  ERP_GESTAO_CLIENTES_EQUIPAMENTOS: "ERP_GESTAO_CLIENTES_EQUIPAMENTOS",
  ERP_GESTAO_CLIENTES_EQUIPAMENTOS_ADD: "ERP_GESTAO_CLIENTES_EQUIPAMENTOS_ADD",
  ERP_GESTAO_CLIENTES_EQUIPAMENTOS_EDIT:
    "ERP_GESTAO_CLIENTES_EQUIPAMENTOS_EDIT",
  ERP_GESTAO_CLIENTES_EQUIPAMENTOS_DELETE:
    "ERP_GESTAO_CLIENTES_EQUIPAMENTOS_DELETE",
  ERP_GESTAO_FINANCEIRO: "ERP_GESTAO_FINANCEIRO",
  ERP_GESTAO_FINANCEIRO_TIPO_SOLICITACOES:
    "ERP_GESTAO_FINANCEIRO_TIPO_SOLICITACOES",
  ERP_GESTAO_FINANCEIRO_TIPO_SOLICITACOES_ADD:
    "ERP_GESTAO_FINANCEIRO_TIPO_SOLICITACOES_ADD",
  ERP_GESTAO_FINANCEIRO_TIPO_SOLICITACOES_EDIT:
    "ERP_GESTAO_FINANCEIRO_TIPO_SOLICITACOES_EDIT",
  ERP_GESTAO_FINANCEIRO_TIPO_SOLICITACOES_DELETE:
    "ERP_GESTAO_FINANCEIRO_TIPO_SOLICITACOES_DELETE",
};

export const ENUM_USAGE_STATUS = {
  DEFAULT: 'DEFAULT',
  COLABORADOR: 'COLABORADOR',
  PROJETOS: 'PROJETOS',
  CLIENTES: 'CLIENTES',
  EQUIPAMENTO_PROJETO: 'EQUIPAMENTO_PROJETO',
  FINANCIAL_REQUEST: 'FINANCIAL_REQUEST',
};

export const ENUM_STATUS = {
  ATIVO: 1,
  INATIVO: 2,
};


export const ENUM_CURRENCY = {
  EUR: "EUR",
  BRL: "BRL",
  USD: "USD",
};
